/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-01-12 12:42:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.client.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607667950211L));
    _jspx_dependants.put("jar:file:/G:/UNIFY-MAVEN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/UNIFY/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Shop online</title>\r\n");
      out.write("<link rel='stylesheet' type='text/css'\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Global Compulsory -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/shop.style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Header and Footer -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/headers/header-v5.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footers/footer-v4.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Implementing Plugins -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/line-icons/line-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/scrollbar/css/jquery.mCustomScrollbar.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/owl-carousel/owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/revolution-slider/rs-plugin/css/settings.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/theme-colors/default.css\"\r\n");
      out.write("\tid=\"style_color\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Customization -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/custom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Subiz -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t(function(s, u, b, i, z) {\r\n");
      out.write("\t\t\tu[i] = u[i] || function() {\r\n");
      out.write("\t\t\t\tu[i].t = +new Date();\r\n");
      out.write("\t\t\t\t(u[i].q = u[i].q || []).push(arguments);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tz = s.createElement('script');\r\n");
      out.write("\t\t\tvar zz = s.getElementsByTagName('script')[0];\r\n");
      out.write("\t\t\tz.async = 1;\r\n");
      out.write("\t\t\tz.src = b;\r\n");
      out.write("\t\t\tz.id = 'subiz-script';\r\n");
      out.write("\t\t\tzz.parentNode.insertBefore(z, zz);\r\n");
      out.write("\t\t})(document, window, 'https://widgetv4.subiz.com/static/js/app.js',\r\n");
      out.write("\t\t\t\t'subiz');\r\n");
      out.write("\t\tsubiz('setAccount', 'acqetkhujxyunuatbxzw');\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- End Subiz -->\r\n");
      out.write("<body class=\"header-fixed\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<!--=== Header v5 ===-->\r\n");
      out.write("\t\t<div class=\"header-v5 header-static\">\r\n");
      out.write("\t\t\t<!-- Topbar v3 -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/client/view/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- End Topbar v3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Navbar -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/client/view/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- End Navbar -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Header v5 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Slider ===-->\r\n");
      out.write("\t\t<div class=\"tp-banner-container\">\r\n");
      out.write("\t\t\t<div class=\"tp-banner\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<!-- SLIDE -->\r\n");
      out.write("\t\t\t\t\t<li class=\"revolution-mch-1\" data-transition=\"fade\"\r\n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"5\" data-masterspeed=\"1000\" data-title=\"Slide 1\">\r\n");
      out.write("\t\t\t\t\t\t<!-- MAIN IMAGE --> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/1.jpg\" alt=\"darkblurbg\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgfit=\"cover\" data-bgposition=\"left top\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch1 sft start\" data-x=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"0\" data-y=\"100\" data-speed=\"1500\" data-start=\"500\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Back.easeInOut\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\tThe New <br> <strong>Collection</strong><br> is here\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption sft\" data-x=\"center\" data-hoffset=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-y=\"380\" data-speed=\"1600\" data-start=\"1800\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END SLIDE -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SLIDE -->\r\n");
      out.write("\t\t\t\t\t<li class=\"revolution-mch-1\" data-transition=\"fade\"\r\n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"5\" data-masterspeed=\"1000\" data-title=\"Slide 2\">\r\n");
      out.write("\t\t\t\t\t\t<!-- MAIN IMAGE --> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/5.jpg\" alt=\"darkblurbg\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgfit=\"cover\" data-bgposition=\"left top\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch3 sft start\" data-x=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"0\" data-y=\"140\" data-speed=\"1500\" data-start=\"500\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Back.easeInOut\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\tLatest <strong>Fashion</strong> Trends\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch4 sft\" data-x=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"-14\" data-y=\"210\" data-speed=\"1400\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-start=\"2000\" data-easing=\"Power4.easeOut\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-captionhidden=\"off\" style=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\tCras non dui et quam auctor pretium.<br> Aenean enim tortr,\r\n");
      out.write("\t\t\t\t\t\t\ttempus et iteus m\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption sft\" data-x=\"center\" data-hoffset=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-y=\"300\" data-speed=\"1600\" data-start=\"1800\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END SLIDE -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SLIDE -->\r\n");
      out.write("\t\t\t\t\t<li class=\"revolution-mch-1\" data-transition=\"fade\"\r\n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"5\" data-masterspeed=\"1000\" data-title=\"Slide 3\">\r\n");
      out.write("\t\t\t\t\t\t<!-- MAIN IMAGE --> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/3.jpg\" alt=\"darkblurbg\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgfit=\"cover\" data-bgposition=\"right top\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch3 sft start\" data-x=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"5\" data-y=\"130\" data-speed=\"1500\" data-start=\"500\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Back.easeInOut\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Luxury</strong> Watches\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch4 sft\" data-x=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"0\" data-y=\"210\" data-speed=\"1400\" data-start=\"2000\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\tlectus. Cras non dui et quam auctor.<br> Aenean enim tortor,\r\n");
      out.write("\t\t\t\t\t\t\ttempus et im\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption sft\" data-x=\"right\" data-hoffset=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-y=\"300\" data-speed=\"1600\" data-start=\"2800\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END SLIDE -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SLIDE -->\r\n");
      out.write("\t\t\t\t\t<li class=\"revolution-mch-1\" data-transition=\"fade\"\r\n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"5\" data-masterspeed=\"1000\" data-title=\"Slide 4\">\r\n");
      out.write("\t\t\t\t\t\t<!-- MAIN IMAGE --> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/2.jpg\" alt=\"darkblurbg\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgfit=\"cover\" data-bgposition=\"left top\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch1 sft start\" data-x=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"0\" data-y=\"100\" data-speed=\"1500\" data-start=\"500\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Back.easeInOut\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\">Girl's Accesories</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch2 sft\" data-x=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"0\" data-y=\"280\" data-speed=\"1400\" data-start=\"2000\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">Super Promo</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption sft\" data-x=\"center\" data-hoffset=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-y=\"370\" data-speed=\"1600\" data-start=\"2800\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">View\r\n");
      out.write("\t\t\t\t\t\t\t\tMore</a> <a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END SLIDE -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SLIDE -->\r\n");
      out.write("\t\t\t\t\t<li class=\"revolution-mch-1\" data-transition=\"fade\"\r\n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"5\" data-masterspeed=\"1000\" data-title=\"Slide 5\">\r\n");
      out.write("\t\t\t\t\t\t<!-- MAIN IMAGE --> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/4.jpg\" alt=\"darkblurbg\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgfit=\"cover\" data-bgposition=\"right top\"\r\n");
      out.write("\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch5 sft start\" data-x=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"5\" data-y=\"130\" data-speed=\"1500\" data-start=\"500\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Back.easeInOut\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Jeans</strong> Collection\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption revolution-ch4 sft\" data-x=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-hoffset=\"-14\" data-y=\"210\" data-speed=\"1400\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-start=\"2000\" data-easing=\"Power4.easeOut\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endspeed=\"300\" data-endeasing=\"Power1.easeIn\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-captionhidden=\"off\" style=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\tCras non dui et quam auctor pretium.<br> Aenean enim tortr,\r\n");
      out.write("\t\t\t\t\t\t\ttempus et iteus m\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- LAYER -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tp-caption sft\" data-x=\"right\" data-hoffset=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-y=\"300\" data-speed=\"1600\" data-start=\"2800\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-easing=\"Power4.easeOut\" data-endspeed=\"300\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-endeasing=\"Power1.easeIn\" data-captionhidden=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"z-index: 6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END SLIDE -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"tp-bannertimer tp-bottom\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Slider ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Product Content ===-->\r\n");
      out.write("\t\t<div class=\"container content-md\">\r\n");
      out.write("\t\t\t<!--=== Illustration v1 ===-->\r\n");
      out.write("\t\t\t<div class=\"row margin-bottom-60\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"illustration-v1 illustration-img1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"illustration-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"illustration-ads ad-details-v1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNEW YEAR <strong>SALE</strong> 30% - 60% <strong>off</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn-u btn-brd btn-brd-hover btn-u-light\" href=\"#\">Shop\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNow</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"illustration-v1 illustration-img2\" href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"illustration-bg\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"illustration-ads ad-details-v2\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"item-time\">Spring 2014</span> <span class=\"item-name\">Lacoste</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end row-->\r\n");
      out.write("\t\t\t<!--=== End Illustration v1 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t<h2>Featured products</h2>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed\r\n");
      out.write("\t\t\t\t\todio elit, ultrices vel cursus sed, placerat ut leo. Phasellus in\r\n");
      out.write("\t\t\t\t\tmagna erat. Etiam gravida convallis augue non tincidunt. Nunc\r\n");
      out.write("\t\t\t\t\tlobortis dapibus neque quis lacinia. Nam dapibus tellus sit amet\r\n");
      out.write("\t\t\t\t\todio venenatis</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--=== Illustration v2 ===-->\r\n");
      out.write("\t\t\t<div class=\"illustration-v2 margin-bottom-60\">\r\n");
      out.write("\t\t\t\t<div class=\"customNavigation margin-bottom-25\">\r\n");
      out.write("\t\t\t\t\t<a class=\"owl-btn prev rounded-x\"><i class=\"fa fa-angle-left\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"owl-btn next rounded-x\"><i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"list-inline owl-slider\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--=== End Illustration v2 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--=== Illustration v3 ===-->\r\n");
      out.write("\t\t\t<div class=\"row margin-bottom-50\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"illustration-v3 illustration-img1\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/category?cate_id=1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"illustration-bg\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"illustration-ads\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"illustration-v3-category\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-category\">Men</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-amount\">56 Items</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"illustration-v3 illustration-img2\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/category?cate_id=2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"illustration-bg\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"illustration-ads\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"illustration-v3-category\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-category\">Women</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-amount\">56 Items</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"illustration-v3 illustration-img3\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/category?cate_id=3\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"illustration-bg\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"illustration-ads\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"illustration-v3-category\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-category\">Children</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"product-amount\">56 Items</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--=== End Illustration v3 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"heading heading-v1 margin-bottom-40\">\r\n");
      out.write("\t\t\t\t<h2>Latest products</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--=== Illustration v2 ===-->\r\n");
      out.write("\t\t\t<div class=\"row illustration-v2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--=== End Illustration v2 ===-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Product Content ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Twitter-Block ===-->\r\n");
      out.write("\t\t<div class=\"parallaxBg twitter-block margin-bottom-60\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t<h2>Latest Tweets</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"carousel-example-generic-v5\" class=\"carousel slide\"\r\n");
      out.write("\t\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active rounded-x\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#carousel-example-generic-v5\" data-slide-to=\"0\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"rounded-x\" data-target=\"#carousel-example-generic-v5\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"rounded-x\" data-target=\"#carousel-example-generic-v5\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tUnify has reached 10000 plus sales and we just want to thank you\r\n");
      out.write("\t\t\t\t\t\t\t\tto our all customers for being part of the Unify Template\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess <a href=\"http://bit.ly/1c0UN3Y\">http://bit.ly/1c0UN3Y</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://twitter.com/htmlstream\">@htmlstream</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline twitter-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-reply\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>the majority have suffered #alteration in some form, by\r\n");
      out.write("\t\t\t\t\t\t\t\tinjected humour, or randomised words which don't look even\r\n");
      out.write("\t\t\t\t\t\t\t\tslightly believable. If you are going to use a passage of Lorem\r\n");
      out.write("\t\t\t\t\t\t\t\tIpsum</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://twitter.com/htmlstream\">@twbootstrap</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline twitter-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-reply\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tNew 100% Free Stock Photos. Every. Single. Day. Everything you\r\n");
      out.write("\t\t\t\t\t\t\t\tneed for your creative projects. <a href=\"#\">http://publicdomainarchive.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://twitter.com/htmlstream\">@wrapbootstrap</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline twitter-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-reply\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-arrow\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"left carousel-control\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#carousel-example-generic-v5\" data-slide=\"prev\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-angle-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"right carousel-control\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#carousel-example-generic-v5\" data-slide=\"next\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Twitter-Block ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!--=== Product Service ===-->\r\n");
      out.write("\t\t\t<div class=\"row margin-bottom-60\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-truck\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Free Delivery</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-earphones-alt\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Customer Service</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-refresh\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Free Returns</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end row-->\r\n");
      out.write("\t\t\t<!--=== End Product Service ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--=== Illustration v4 ===-->\r\n");
      out.write("\t\t\t<div class=\"row illustration-v4 margin-bottom-40\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Top Rated</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/08.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price line-through\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$65.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/09.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/03.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Best Sellers</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/02.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/10.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/06.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price line-through\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$65.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 padding\">\r\n");
      out.write("\t\t\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Sale Items</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/07.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price line-through\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$65.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/04.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"thumb-product\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"thumb-product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/05.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thumb-product-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"shop-ui-inner.html\">Yuketen</a> – <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"shop-ui-inner.html\">Derby Shoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"thumb-product-type\">Footwear - Oxfords</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-price\">$75.00</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"thumb-product-purchase\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i></a> | <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end row-->\r\n");
      out.write("\t\t\t<!--=== End Illustration v4 ===-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/end cotnainer-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Collection Banner ===-->\r\n");
      out.write("\t\t<div class=\"collection-banner\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7 md-margin-bottom-50\">\r\n");
      out.write("\t\t\t\t\t<h2>Makeup collection</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tDuis in posuere risus. Vivamus sed dignissim tellus. In vehicula\r\n");
      out.write("\t\t\t\t\t\tjusto tempor commodo. <br> Nunc lobortis dapibus neque quis\r\n");
      out.write("\t\t\t\t\t\tlacinia\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<br> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn-u btn-brd btn-brd-hover btn-u-light\">Shop Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overflow-h\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"percent-numb\">50</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"percent-off\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"discount-percent\">%</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"discount-off\">off</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"new-offers shop-bg-green rounded-x\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>new</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Products</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Collection Banner ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Sponsors ===-->\r\n");
      out.write("\t\t<div class=\"container content\">\r\n");
      out.write("\t\t\t<div class=\"heading heading-v1 margin-bottom-40\">\r\n");
      out.write("\t\t\t\t<h2>Sponsors</h2>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed\r\n");
      out.write("\t\t\t\t\todio elit, ultrices vel cursus sed, placerat ut leo. Phasellus in\r\n");
      out.write("\t\t\t\t\tmagna erat. Etiam gravida convallis augue non tincidunt. Nunc\r\n");
      out.write("\t\t\t\t\tlobortis dapibus neque quis lacinia. Nam dapibus tellus sit amet\r\n");
      out.write("\t\t\t\t\todio venenatis</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"list-inline owl-slider-v2\">\r\n");
      out.write("\t\t\t\t<li class=\"item first-child\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/07.png\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/08.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/10.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/11.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/09.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/12.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/07.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/08.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/09.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/10.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/11.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/clients/12.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!--/end owl-carousel-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Sponsors ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Shop Suvbscribe ===-->\r\n");
      out.write("\t\t<div class=\"shop-subscribe\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 md-margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\tsubscribe to our weekly <strong>newsletter</strong>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Email your email...\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end container-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Shop Suvbscribe ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Footer v4 ===-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/client/view/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--=== End Footer v4 ===-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/wrapper-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS Global Compulsory -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- JS Implementing Plugins -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/back-to-top.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/smoothScroll.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/jquery.parallax.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/owl-carousel/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/scrollbar/js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/revolution-slider/rs-plugin/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("\t<!-- JS Customization -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/custom.js\"></script>\r\n");
      out.write("\t<!-- JS Page Level -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/shop.app.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/owl-carousel.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/revolution-slider.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function() {\r\n");
      out.write("\t\t\tApp.init();\r\n");
      out.write("\t\t\tApp.initScrollBar();\r\n");
      out.write("\t\t\tApp.initParallaxBg();\r\n");
      out.write("\t\t\tOwlCarousel.initOwlCarousel();\r\n");
      out.write("\t\t\tRevolutionSlider.initRSfullWidth();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/respond.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/placeholder-IE-fixes.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/client/view/index.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/client/static");
      // /view/client/view/index.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("url");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view/client/view/index.jsp(283,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/client/view/index.jsp(283,5) '${pwelcome }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pwelcome }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /view/client/view/index.jsp(283,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<li class=\"item\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"product-img\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<a\r\n");
            out.write("\t\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><img\r\n");
            out.write("\t\t\t\t\t\t\t\t\twidth=\"314\" height=\"414\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\"></a> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\tclass=\"product-review\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Quick\r\n");
            out.write("\t\t\t\t\t\t\t\t\treview</a> <a class=\"add-to-cart\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i\r\n");
            out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>Add to cart</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"shop-rgba-red rgba-banner\">Out of stock</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"product-description product-description-brd\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"overflow-h margin-bottom-5\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"gender text-uppercase\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.category.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"gender\">best selling</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-price\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title-price\">$ ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li class=\"like-icon\"><a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Add to wishlist\" data-toggle=\"tooltip\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tdata-placement=\"left\" class=\"tooltips\" href=\"#\"><i\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/client/view/index.jsp(284,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/image?fname=${p.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/client/view/index.jsp(284,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("imgUrl");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /view/client/view/index.jsp(385,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/view/client/view/index.jsp(385,4) '${pwelcome }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pwelcome }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /view/client/view/index.jsp(385,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            if (_jspx_meth_c_005furl_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-6 md-margin-bottom-30\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"product-img\">\r\n");
            out.write("\t\t\t\t\t\t\t<a\r\n");
            out.write("\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><img\r\n");
            out.write("\t\t\t\t\t\t\t\twidth=\"314\" height=\"414\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\"\r\n");
            out.write("\t\t\t\t\t\t\talt=\"\"></a> <a class=\"product-review\"\r\n");
            out.write("\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Quick\r\n");
            out.write("\t\t\t\t\t\t\t\treview</a> <a class=\"add-to-cart\"\r\n");
            out.write("\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>Add to cart</a>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"product-description product-description-brd\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"overflow-h margin-bottom-5\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product/detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"gender text-uppercase\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.category.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"gender\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.des }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"product-price\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"title-price\">$ ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<li class=\"like-icon\"><a\r\n");
            out.write("\t\t\t\t\t\t\t\t\tdata-original-title=\"Add to wishlist\" data-toggle=\"tooltip\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"left\" class=\"tooltips\" href=\"#\"><i\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart\"></i></a></li>\r\n");
            out.write("\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /view/client/view/index.jsp(386,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/image?fname=${p.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/client/view/index.jsp(386,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setVar("imgUrl");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
