/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-01-12 18:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.client.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607667950211L));
    _jspx_dependants.put("jar:file:/G:/UNIFY-MAVEN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/UNIFY/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Product Details</title>\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Web Fonts -->\r\n");
      out.write("<link rel='stylesheet' type='text/css'\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Global Compulsory -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/shop.style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Header and Footer -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/headers/header-v5.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footers/footer-v4.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Implementing Plugins -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/line-icons/line-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/scrollbar/css/jquery.mCustomScrollbar.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/owl-carousel/owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/sky-forms-pro/skyforms/css/sky-forms.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/master-slider/quick-start/masterslider/style/masterslider.css\">\r\n");
      out.write("<link rel='stylesheet'\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/master-slider/quick-start/masterslider/skins/default/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Style Switcher -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/style-switcher.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/theme-colors/default.css\"\r\n");
      out.write("\tid=\"style_color\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Customization -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/custom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body class=\"header-fixed\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<!--=== Header v5 ===-->\r\n");
      out.write("\t\t<div class=\"header-v5 header-static\">\r\n");
      out.write("\t\t\t<!-- Topbar v3 -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- End Topbar v3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Navbar -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- End Navbar -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Header v5 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Shop Product ===-->\r\n");
      out.write("\t\t<div class=\"shop-product\">\r\n");
      out.write("\t\t\t<!-- Breadcrumbs v5 -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ul class=\"breadcrumb-v5\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\"><i class=\"fa fa-home\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Products</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">Detail</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Breadcrumbs v5 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 md-margin-bottom-50\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ms-showcase2-template\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Master Slider -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"master-slider ms-skin-default\" id=\"masterslider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"ms-brd\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/blank.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- End Master Slider -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"shop-product-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline shop-product-social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-pinterest\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--/end shop product social-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline product-ratings margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"product-review-list\"><span>(1) <a href=\"#\">Review</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t| <a href=\"#\"> Add Review</a></span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!--/end shop product ratings-->\r\n");
      out.write("\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.des }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline shop-product-prices margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shop-red\">$ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".0</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"line-through\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price * 1.25 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><small class=\"shop-bg-red time-day-left\"> Best\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSale </small></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!--/end shop product prices-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"shop-product-title\">Size</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline product-size margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"size-1\" name=\"size\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"size-1\">S</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"size-2\" name=\"size\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"size-2\">M</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"size-3\" name=\"size\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"size-3\">L</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"size-4\" name=\"size\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"size-4\">XL</label></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!--/end product size-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"shop-product-title\">Color</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline product-color margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"color-1\" name=\"color\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"color-one\" for=\"color-1\"></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"color-2\" name=\"color\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"color-two\" for=\"color-2\"></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"radio\" id=\"color-3\" name=\"color\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"color-three\" for=\"color-3\"></label></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!--/end product color-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"shop-product-title\">Quantity</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"margin-bottom-40\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form name=\"f1\" class=\"product-quantity sm-margin-bottom-20\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod=\"get\" action=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"pId\" hidden=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type='button' class=\"quantity-button\" name='subtract'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick='javascript: subtractQty();' value='-'>-</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type='text' class=\"quantity-field\" name='quantity'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"1\" id='qty' />\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type='button' class=\"quantity-button\" name='add'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick='javascript: document.getElementById(\"qty\").value++;'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue='+'>+</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn-u btn-u-sea-shop btn-u-lg\">Add\r\n");
      out.write("\t\t\t\t\t\t\t\t\tto Cart</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--/end product quantity-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline add-to-wishlist add-to-wishlist-brd\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"wishlist-in\"><i class=\"fa fa-heart\"></i> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">Add to Wishlist</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"compare-in\"><i class=\"fa fa-exchange\"></i> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">Add to Compare</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"wishlist-category\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Categories:</strong> <a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.category.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/end row-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Shop Product ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Content Medium ===-->\r\n");
      out.write("\t\t<div class=\"content-md container\">\r\n");
      out.write("\t\t\t<!--=== Product Service ===-->\r\n");
      out.write("\t\t\t<div class=\"row margin-bottom-60\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-truck\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Free Delivery</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service md-margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-earphones-alt\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Customer Service</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 product-service\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-refresh\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"product-service-in\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Free Returns</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Integer mattis lacinia felis vel molestie. Ut eu euismod\r\n");
      out.write("\t\t\t\t\t\t\terat, tincidunt pulvinar semper veliUt porta, leo...</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">+Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end row-->\r\n");
      out.write("\t\t\t<!--=== End Product Service ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tab-v5\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#description\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"tab\">Description</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#reviews\" role=\"tab\" data-toggle=\"tab\">Reviews\r\n");
      out.write("\t\t\t\t\t\t\t(1)</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<!-- Description -->\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane fade in active\" id=\"description\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Morbi non semper est, eget tincidunt turpis. Vivamus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsollicitudin sodales nisi, et venenatis turpis Vivamus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsollicitudin ultricies eget. Fusce vitae neque blandit lectus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfaucibus aliquet nec vel ipsum. Integer mattis lacinia felis\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvel sollicitudin molestie.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"heading-md margin-bottom-20\">Specifies</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled specifies-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Brand Name: <span>Lacoste</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Technics: <span>Computer</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tKnitted</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Sleeve Length: <span>Full</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Sleeve Style: <span>Regular</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Pattern Type: <span>PAID</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Style: <span>Casual</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled specifies-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Material: <span>Cotton,Nylon</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Item Type: <span>Pullovers</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Thickness: <span>Thin</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Model Number: <span>TM-11013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>Gender: <span>Men</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i>MATERIAL: <span>80%COTTON+10%NYLON</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"responsive-video\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<iframe src=\"//player.vimeo.com/video/72343553\" frameborder=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twebkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- End Description -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Reviews -->\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane fade\" id=\"reviews\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-comment margin-bottom-40\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-comment-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"product-comment-img rounded-x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/team/01.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-comment-dtl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tMickel <small>22 days ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>I like the green colour, it's very likeable and reminds\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tme of Hollister. A little loose though but I am very skinny</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"reply\"><a href=\"#\">Reply</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"heading-md margin-bottom-30\">Add a review</h3>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/php/demo-contacts-process.php\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"sky-form3\" class=\"sky-form sky-changes-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"label-v2\">Name</label> <label class=\"input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"label-v2\">Email</label> <label class=\"input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"label-v2\">Review</label> <label class=\"textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"7\" name=\"message\" id=\"message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<footer class=\"review-submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"label-v2\">Review</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"stars-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"stars-rating\" id=\"stars-rating-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"stars-rating-5\"><i class=\"fa fa-star\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"stars-rating\" id=\"stars-rating-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"stars-rating-4\"><i class=\"fa fa-star\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"stars-rating\" id=\"stars-rating-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"stars-rating-3\"><i class=\"fa fa-star\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"stars-rating\" id=\"stars-rating-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"stars-rating-2\"><i class=\"fa fa-star\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"stars-rating\" id=\"stars-rating-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"stars-rating-1\"><i class=\"fa fa-star\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn-u btn-u-sea-shop btn-u-sm pull-right\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- End Reviews -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/end container-->\r\n");
      out.write("\t\t<!--=== End Content Medium ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Illustration v2 ===-->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"heading heading-v1 margin-bottom-20\">\r\n");
      out.write("\t\t\t\t<h2>Product you may like</h2>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed\r\n");
      out.write("\t\t\t\t\todio elit, ultrices vel cursus sed, placerat ut leo. Phasellus in\r\n");
      out.write("\t\t\t\t\tmagna erat. Etiam gravida convallis augue non tincidunt. Nunc\r\n");
      out.write("\t\t\t\t\tlobortis dapibus neque quis lacinia. Nam dapibus tellus sit amet\r\n");
      out.write("\t\t\t\t\todio venenatis</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"illustration-v2 margin-bottom-60\">\r\n");
      out.write("\t\t\t\t<div class=\"customNavigation margin-bottom-25\">\r\n");
      out.write("\t\t\t\t\t<a class=\"owl-btn prev rounded-x\"><i class=\"fa fa-angle-left\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"owl-btn next rounded-x\"><i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"list-inline owl-slider-v4\">\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/09.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/07.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$60.00</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"title-price line-through\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/08.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/06.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/04.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a href=\"#\"><img class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/thumb/03.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-description-v2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Double-breasted</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title-price\">$95.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline product-ratings\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating-selected fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"rating fa fa-star\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Illustration v2 ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Shop Suvbscribe ===-->\r\n");
      out.write("\t\t<div class=\"shop-subscribe\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 md-margin-bottom-20\">\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\tsubscribe to our weekly <strong>newsletter</strong>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Email your email...\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/end container-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--=== End Shop Suvbscribe ===-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=== Footer v4 ===-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--=== End Footer v4 ===-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/wrapper-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS Global Compulsory -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- JS Implementing Plugins -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/back-to-top.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/smoothScroll.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/owl-carousel/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/scrollbar/js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\t<!-- Master Slider -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/master-slider/quick-start/masterslider/masterslider.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/master-slider/quick-start/masterslider/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<!-- JS Customization -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/custom.js\"></script>\r\n");
      out.write("\t<!-- JS Page Level -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/shop.app.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/owl-carousel.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/master-slider.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/forms/product-quantity.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function() {\r\n");
      out.write("\t\t\tApp.init();\r\n");
      out.write("\t\t\tApp.initScrollBar();\r\n");
      out.write("\t\t\tOwlCarousel.initOwlCarousel();\r\n");
      out.write("\t\t\tMasterSliderShowcase2.initMasterSliderShowcase2();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/respond.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/placeholder-IE-fixes.js\"></script>    \r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/client/view/product-detail.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/client/static");
      // /view/client/view/product-detail.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("url");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /view/client/view/product-detail.jsp(88,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/image?fname=${product.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/client/view/product-detail.jsp(88,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("imgUrl");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /view/client/view/product-detail.jsp(159,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/member/cart/add");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
